name: Docker nightly build

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build_image:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_CONTAINER_UNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build docker image
        run: |
          docker build . --pull --no-cache -t ghcr.io/brooooooklyn/canvas/ubuntu-builder:focal
          docker build . --pull --no-cache -f musl.Dockerfile -t ghcr.io/brooooooklyn/canvas/musl-builder:lts

      - name: Push docker image
        run: |
          docker push ghcr.io/brooooooklyn/canvas/ubuntu-builder:focal
          docker push ghcr.io/brooooooklyn/canvas/musl-builder:lts
