name: Docker nightly build

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build_image:
    name: Build debian-builder:stretch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to registry
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker build . --pull -t docker.pkg.github.com/brooooooklyn/canvas/debian-builder:stretch
          docker build . --pull --no-cache -f musl.Dockerfile -t docker.pkg.github.com/brooooooklyn/canvas/musl-builder:lts
      - name: Push docker image
        run: |
          docker push docker.pkg.github.com/brooooooklyn/canvas/debian-builder:stretch
          docker push docker.pkg.github.com/brooooooklyn/canvas/musl-builder:lts
