name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint SourceCode
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: Install nasm
        uses: ilammy/setup-nasm@v1

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          override: true
          components: rustfmt, clippy

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: lint-cargo-registry

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: lint-cargo-index

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-lint-linux-x64-gnu

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Download skia binary
        run: node ./scripts/release-skia-binary.js --download

      - name: 'Lint JS/TS'
        run: pnpm lint

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
