name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint SourceCode
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/brooooooklyn/canvas/ubuntu-builder:focal

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: 'yarn'

      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
          toolchain: nightly-2023-02-10
          components: clippy, rustfmt

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: lint-cargo-cache

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Download skia binary
        run: |
          git config --global --add safe.directory $(pwd)
          node ./scripts/release-skia-binary.js --download

      - name: 'Lint JS/TS'
        run: yarn lint

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
